systemLog:
    destination: file
    path: "{path to coding test folder}\\log\\mongo.log"
    logAppend: true
storage:
    dbPath: "{path to coding test folder}\\data\\db"
    journal:
        enabled: true
net:
    bindIp: 127.0.0.1
    port: 27017
